### ISSUE TITLE
Task doesn't handle 384 well plates: Rows after H are an issue

### ISSUE THREAD

**Issue by jluethi** [jluethi/fractal-faim-hcs#13]
It looks like the parser is currently only written for 96 well plates

Example data available here:
`BasePath in no backup /maehmari/MK_210805_005-03_subset`

Error:

```
TASK ERROR:Task id: 136 (Create OME-Zarr MD), e.workflow_task_order=0
TRACEBACK:
Traceback (most recent call last):
  File "BASEPATH/server-envs/fractal-server-1.3.2/lib64/python3.9/site-packages/fractal_server/app/runner/_common.py", line 262, in call_single_task
    raise e
  File "BASEPATH/server-envs/fractal-server-1.3.2/lib64/python3.9/site-packages/fractal_server/app/runner/_common.py", line 255, in call_single_task
    _call_command_wrapper(
  File "BASEPATH/server-envs/fractal-server-1.3.2/lib64/python3.9/site-packages/fractal_server/app/runner/_common.py", line 172, in _call_command_wrapper
    raise TaskExecutionError(err)
fractal_server.app.runner.common.TaskExecutionError: 2023-08-03 14:08:46,240; INFO; START create_ome_zarr_md task
Traceback (most recent call last):
  File "BASEPATH/FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.1.dev27+g1458b59/venv/lib/python3.9/site-packages/fractal_faim_hcs/create_ome_zarr_md.py", line 101, in <module>
    run_fractal_task(
  File "BASEPATH/FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.1.dev27+g1458b59/venv/lib64/python3.9/site-packages/fractal_tasks_core/tasks/_utils.py", line 76, in run_fractal_task
    metadata_update = task_function(**pars)
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "BASEPATH/FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.1.dev27+g1458b59/venv/lib/python3.9/site-packages/fractal_faim_hcs/create_ome_zarr_md.py", line 67, in create_ome_zarr_md
    build_zarr_scaffold(
  File "BASEPATH/FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.1.dev27+g1458b59/venv/lib64/python3.9/site-packages/faim_hcs/Zarr.py", line 147, in build_zarr_scaffold
    plate = _create_zarr_plate(
  File "BASEPATH/FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.1.dev27+g1458b59/venv/lib64/python3.9/site-packages/faim_hcs/Zarr.py", line 92, in _create_zarr_plate
    write_plate_metadata(
  File "BASEPATH/FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.1.dev27+g1458b59/venv/lib64/python3.9/site-packages/ome_zarr/writer.py", line 378, in write_plate_metadata
    "wells": _validate_plate_wells(wells, rows, columns, fmt=fmt),
  File "BASEPATH/FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.1.dev27+g1458b59/venv/lib64/python3.9/site-packages/ome_zarr/writer.py", line 160, in _validate_plate_wells
    well_dict = fmt.generate_well_dict(well, rows, columns)
  File "BASEPATH/FRACTAL_TASK_DIR/.fractal/fractal_faim_hcs0.1.dev27+g1458b59/venv/lib64/python3.9/site-packages/ome_zarr/format.py", line 233, in generate_well_dict
    raise ValueError("%s is not defined in the list of rows", row)
ValueError: ('%s is not defined in the list of rows', 'K')
```

cc Marius

We probably need to have a contribution to the upstream faim-hcs library and maybe an option provided to the task on what plate layout is used.

**Comment by jluethi** [comment]
There is a `PlateLayout` Enum in faim-hcs, see https://github.com/fmi-faim/faim-hcs/blob/d106436521a6abcc41bb7748c08a22057480e3f9/src/faim_hcs/Zarr.py#L24
It's exposed in `build_zarr_scaffold` here: https://github.com/fmi-faim/faim-hcs/blob/d106436521a6abcc41bb7748c08a22057480e3f9/src/faim_hcs/Zarr.py#L121

We need to expose this in the `create_ome_zarr_md.py` task, then it should work :)
